routes/web.php
<?php

Route::get('/', 'FrontEndController@index')->name('main-page');
Route::get('/about', 'FrontEndController@about')->name('about');
Route::get('/singlepage/{slug}', 'FrontEndController@single')->name('single');
Route::get('/category/{name}', 'FrontEndController@category')->name('category');
Route::get('/results', function(){
        $posts = \App\Post::where('title', 'like', '%' . request('query') . '%')->get();
        return  view('vatiz-front.results')->with('posts', $posts)
                    ->with('title', 'Search results for : ' . request('query'))
                    ->with('query', request('query'));
}) -> name('results');

Auth::routes(['register'=>false]);
Route::get('/register', 'FrontEndController@index');

Route::group(['middleware' => 'auth', 'prefix'=>'admin'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/posts/trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::get('/posts/trash/{id}', 'PostsController@trash')->name('posts.trash');
    Route::get('/posts/restore/{id}', 'PostsController@restore')->name('posts.restore');
    Route::get('/posts/delete/{id}', 'PostsController@delete')->name('posts.delete');
    Route::resource('posts', 'PostsController');

    Route::get('/categories/delete/{id}', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('categories', 'CategoriesController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
	Route::post('/settings/update', 'SettingsController@update') -> name('settings.update');
    Route::get('/settings/changepw', 'SettingsController@password') -> name('settings.changepw');
    Route::post('/settings/updatepassword', 'SettingsController@updatepassword') -> name('settings.updatepassword');

});

resources/views/vatiz-back/layouts/back-footer.blade.php
<section>
 <!-- footer -->
		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>

resources/views/vatiz-back/layouts/back-header.blade.php
<!--header start-->
<header class="header fixed-top clearfix">
<!--logo start-->
<div class="brand">
    <a href="{{ route('main-page') }}" class="logo">
        Bhatiz
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>
<!--logo end-->
<div class="nav notify-row" id="top_menu">
</div>
<div class="top-nav clearfix">
    <span style="color:red">Total Unique Visitor(s) : {{ $visitors->count() }} </span>
    <ul class="nav pull-right top-menu">
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="images/2.png">
                <span class="username">{{ Auth::user() -> name }}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="{{ route('settings.changepw') }}"><i class="fa fa-cog"></i>Change Password</a></li>
                <li>
                <a class="dropdown-item" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();"> <i class="fa fa-key"></i>
                            		{{ __('Logout') }}
                                    </a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                  </form>
              </a></li>
            </ul>
        </li>
        <!-- user login dropdown end -->

    </ul>
    <!--search & user info end-->
</div>
</header>

resources/views/vatiz-back/layouts/footer.blade.php
<script src="{{ asset('back/js/bootstrap.js') }}"></script>
<script src="{{ asset('back/js/jquery.dcjqaccordion.2.7.js') }}"></script>
<script src="{{ asset('back/js/scripts.js') }}"></script>
<script src="{{ asset('back/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('back/js/jquery.nicescroll.js') }}"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="{{ asset('back/js/flot-chart/excanvas.min.js') }}"></script><![endif]-->
<script src="{{ asset('back/js/jquery.scrollTo.js') }}"></script>
<!-- morris JavaScript -->

resources/views/vatiz-back/layouts/header.blade.php
<head>
<title>Bhatij Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="#" />

<link rel="icon" href="{{ asset('logo/final.png') }}" type="image/icon type">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- bootstrap-css -->
<link rel="stylesheet" href="{{ asset('back/css/bootstrap.min.css') }}" >
<!-- Custom CSS -->
<link href="{{ asset('back/css/style.css') }}" rel='stylesheet' type='text/css' />
<link href="{{ asset('back/css/style-responsive.css') }}" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="{{ asset('back/css/font.css') }}" type="text/css"/>
<link href="{{ asset('back/css/font-awesome.css') }}" rel="stylesheet">

<script src="{{ asset('back/js/jquery2.0.3.min.js') }}"></script>
<link rel="stylesheet" href="{{ asset('back/css/toastr.css') }}" />

</head>
<body>

resources/views/vatiz-back/layouts/layout.blade.php
<!DOCTYPE html>

@include('vatiz-back.layouts.header')
@yield('header')
<body>

@yield('content')

@include('vatiz-back.layouts.footer')

@yield('footer')
@include('partials.toastr')
</body>
</html>

resources/views/vatiz-back/layouts/sidebar.blade.php
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="#">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>


                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-bullhorn"></i>
                        <span>Categories</span>
                    </a>
                    <ul class="sub">
                        <li><a href="{{ route('categories.index') }}">Categories</a></li>
                        <li><a href="{{ route('categories.create') }}">Create Category</a></li>
                    </ul>
                </li>


                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Blog Posts</span>
                    </a>
                    <ul class="sub">
						<li><a href="{{ route('posts.index') }}">Posts</a></li>
                        <li><a href="{{ route('posts.create') }}">Create Post</a></li>
                        <li><a href="{{ route('posts.trashed') }}">Trashed Posts</a></li>
                    </ul>
                </li>

                <li>
                    <a href="{{ route('settings.index') }}">
                        <i class="fa fa-user"></i>
                        <span>Site Settings</span>
                    </a>
                </li>

{{--                 <li>
                    <a href="fontawesome.html">
                        <i class="fa fa-bullhorn"></i>
                        <span>Font awesome </span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-th"></i>
                        <span>Data Tables</span>
                    </a>
                    <ul class="sub">
                        <li><a href="basic_table.html">Basic Table</a></li>
                        <li><a href="responsive_table.html">Responsive Table</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-tasks"></i>
                        <span>Form Components</span>
                    </a>
                    <ul class="sub">
                        <li><a href="form_component.html">Form Elements</a></li>
                        <li><a href="form_validation.html">Form Validation</a></li>
						<li><a href="dropzone.html">Dropzone</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-envelope"></i>
                        <span>Mail </span>
                    </a>
                    <ul class="sub">
                        <li><a href="mail.html">Inbox</a></li>
                        <li><a href="mail_compose.html">Compose Mail</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class=" fa fa-bar-chart-o"></i>
                        <span>Charts</span>
                    </a>
                    <ul class="sub">
                        <li><a href="chartjs.html">Chart js</a></li>
                        <li><a href="flot_chart.html">Flot Charts</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class=" fa fa-bar-chart-o"></i>
                        <span>Maps</span>
                    </a>
                    <ul class="sub">
                        <li><a href="google_map.html">Google Map</a></li>
                        <li><a href="vector_map.html">Vector Map</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-glass"></i>
                        <span>Extra</span>
                    </a>
                    <ul class="sub">
                        <li><a href="gallery.html">Gallery</a></li>
						<li><a href="404.html">404 Error</a></li>
                        <li><a href="registration.html">Registration</a></li>
                    </ul>
                </li>
                <li>
                    <a href="login.html">
                        <i class="fa fa-user"></i>
                        <span>Login Page</span>
                    </a>
                </li> --}}
            </ul>            </div>
        <!-- sidebar menu end-->
    </div>
</aside>