routes/web.php
<?php

Route::get('/', 'FrontEndController@index')->name('main-page');
Route::get('/about', 'FrontEndController@about')->name('about');
Route::get('/singlepage/{slug}', 'FrontEndController@single')->name('single');
Route::get('/category/{name}', 'FrontEndController@category')->name('category');
Route::get('/results', function(){
        $posts = \App\Post::where('title', 'like', '%' . request('query') . '%')->get();
        return  view('vatiz-front.results')->with('posts', $posts)
                    ->with('title', 'Search results for : ' . request('query'))
                    ->with('query', request('query'));
}) -> name('results');

Auth::routes(['register'=>false]);
Route::get('/register', 'FrontEndController@index');

Route::group(['middleware' => 'auth', 'prefix'=>'admin'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/posts/trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::get('/posts/trash/{id}', 'PostsController@trash')->name('posts.trash');
    Route::get('/posts/restore/{id}', 'PostsController@restore')->name('posts.restore');
    Route::get('/posts/delete/{id}', 'PostsController@delete')->name('posts.delete');
    Route::resource('posts', 'PostsController');

    Route::get('/categories/delete/{id}', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('categories', 'CategoriesController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
	Route::post('/settings/update', 'SettingsController@update') -> name('settings.update');
    Route::get('/settings/changepw', 'SettingsController@password') -> name('settings.changepw');
    Route::post('/settings/updatepassword', 'SettingsController@updatepassword') -> name('settings.updatepassword');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug'];

    public function posts()
    {
    	return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('vatiz-back.categories.index')
        		->with('categories', Category::latest()->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vatiz-back.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only(['name']);
        $data['slug'] = str_slug($request->name);

       $this -> validate($request, [
            'name'   => 'required|unique:categories'
       ]);

        $result = Category::create($data);
        if($result) {
            session()->flash('success', 'Category Created Successfully!');
        } else {
            session()->flash('error', 'Something went wrong.');
        }

        return redirect() -> route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('vatiz-back.categories.show')
                    ->with('category', $category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit') -> with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->only(['name']);
        $data['slug'] = str_slug($request->name);

        $this -> validate($request, [
            'name'   => 'required'
       	]);

         $result = $category->update($data);

         if($result) {
           session()->flash('status', 'Category Updated Successfully!');
         } else {
           session()->flash('error', 'Something went wrong.');
         }

         return redirect() -> route('categories.index') ;
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $category = Category::findOrFail($id);
        foreach ($category->posts as $post) {
            $post -> delete();
        }
        $result = $category->delete();

         if($result) {
           session()->flash('success', 'Category Deleted Successfully!');
         } else {
           session()->flash('error', 'Something went wrong.');
         }

         return redirect() -> route('categories.index') ;
    }
}

resources/views/vatiz-back/categories/create.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<style>
header.panel-heading.custom {
    background: antiquewhite;
    color: sienna;
    font-size: x-large;
    font-family: sans-serif;
    font-weight: 600;
    box-shadow: 3px 3px darkolivegreen;
}

.alert.alert-danger {
    color: firebrick;
    font-size: 16px;
    font-family: sans-serif;
}
</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
	 <div class="panel panel-default">
    <div class="panel-heading">
    @if(isset($category))
     Edit Category
    @else
     Create a New Category
    @endif
    </div>

 	@include('partials.errors')
 	<div class="custom" style="padding: 12px">
 		@if(isset($category))
		{!! Form::model($category, ['method'=>'PATCH', 'route' => ['categories.update', $category->id]]) !!}
		@else
		{{ Form::open(array('method'=>'POST','route' => 'categories.store')) }}
		@endif
		<div class="form-group">
			{!! Form::label('category', 'Category : ', ['class' => 'font-weight-bold']) !!}
			{!! Form::text('name', isset($category) ? $category->name : ' ' , ['class' => 'form-control','placeholder'=>'Enter title']) !!}
		</div>

		<div class="form-group right">
			{{ Form::submit(isset($category) ? 'Update category' : 'Create category',['class' => 'btn btn-success'])}}
		</div>
		{!! Form::close() !!}
 	</div>
@include('vatiz-back.layouts.back-footer')
</section>
@endsection

resources/views/vatiz-back/categories/index.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<style>
	.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
    background: aliceblue;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
	color: royalblue;
}

a:focus, a:hover {
    color: chocolate;
    font-weight: 600;
}

</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     List of All Categories
    </div>
    <div>
      <table class="table">
        <thead>
          <tr>
            <th>Category Name</th>
            <th>Editing</th>
            <th>Delete</th>
          </tr>
        </thead>
        @if($categories)
        <tbody>
        @foreach($categories as $category)
          <tr>
            <td>
              <a href="{{ route('categories.show', $category->id) }}">{{ $category->name }}</a>
            </td>
      			<td><a href="{{ route('categories.edit', $category -> id) }}" class="btn btn-sm btn-info">Edit</a></td>

      			<td><a href="{{ route('categories.delete', $category -> id) }}" class="btn btn-sm btn-danger">Delete</a></td>
					</tr>
          </tr>
        @endforeach
        </tbody>
        @endif
      </table>
    </div>
  </div>
</div>

		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>
@endsection

resources/views/vatiz-back/categories/show.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<style>
	.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
    background: aliceblue;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
	color: royalblue;
}
.jumbotron.col-md-6 {
    border: 1px solid tomato;
}

a:focus, a:hover {
    color: chocolate;
    font-weight: 600;
}

.jumbotron p {
    margin-bottom: 15px;
    font-size: 16px;
    color: teal;
    font-weight: 500;
}

</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
 <div class="panel panel-default">
    <div class="panel-heading">
    Category -> {{ $category->name }}
    </div>
    @if($category->posts)
    @foreach($category->posts as $post)
    <div class="jumbotron col-md-6" style="padding:4px;margin-top: 4px;margin-bottom: 0px;">
      <img src="{{ asset($post->image) }}" alt="" height="100px" width="200px">
      <a href="{{ route('posts.show', $post->id) }}" class="btn btn-info btn-sm pull-right">View Post</a>
      <div class="clearfix"> </div>
      <span>Title :<p>{!!strlen($post->title) > 70 ? substr($post->title,0,70) : $post->title !!}</p>
      </span>
      Description : <p>{!!strlen($post->description) > 70 ? substr($post->description,0,70) : $post->description !!}</p>
    </div>
    @endforeach
    @endif
</div>

<div class="row">

</div>


		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>
@endsection