routes/web.php
<?php

Route::get('/', 'FrontEndController@index')->name('main-page');
Route::get('/about', 'FrontEndController@about')->name('about');
Route::get('/singlepage/{slug}', 'FrontEndController@single')->name('single');
Route::get('/category/{name}', 'FrontEndController@category')->name('category');
Route::get('/results', function(){
        $posts = \App\Post::where('title', 'like', '%' . request('query') . '%')->get();
        return  view('vatiz-front.results')->with('posts', $posts)
                    ->with('title', 'Search results for : ' . request('query'))
                    ->with('query', request('query'));
}) -> name('results');

Auth::routes(['register'=>false]);
Route::get('/register', 'FrontEndController@index');

Route::group(['middleware' => 'auth', 'prefix'=>'admin'], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/posts/trashed', 'PostsController@trashed')->name('posts.trashed');
    Route::get('/posts/trash/{id}', 'PostsController@trash')->name('posts.trash');
    Route::get('/posts/restore/{id}', 'PostsController@restore')->name('posts.restore');
    Route::get('/posts/delete/{id}', 'PostsController@delete')->name('posts.delete');
    Route::resource('posts', 'PostsController');

    Route::get('/categories/delete/{id}', 'CategoriesController@delete')->name('categories.delete');
    Route::resource('categories', 'CategoriesController');

    Route::get('/settings', 'SettingsController@index')->name('settings.index');
	Route::post('/settings/update', 'SettingsController@update') -> name('settings.update');
    Route::get('/settings/changepw', 'SettingsController@password') -> name('settings.changepw');
    Route::post('/settings/updatepassword', 'SettingsController@updatepassword') -> name('settings.updatepassword');

});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Post extends Model
{
    public $path = '/uploads/posts/';

	use SoftDeletes;

    protected $dates = ['deleted_at', 'published_at'];

	protected $fillable = [
        'title',
		'description',
		'slug',
        'image',
        'category_id',
        'author'
    ];

	public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getImageAttribute($value){
        return $this->path . $value;
    }

    public function uploadImage($image)
    {
        $img = strtolower(preg_replace('/\s+/','-',$image -> getClientOriginalName()));
        $time = strtolower(preg_replace('/\s+/','-', time()));
        $name =  $time .'-'. $img ;

        $image->move('uploads/posts/', $name);

        return $name;
    }

    public function deleteImage($image)
    {
        $root = realpath($_SERVER['DOCUMENT_ROOT']);
        $post_image = $root . $image;
        if(unlink($post_image)){
            return true;
        }
        return false;
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CreatePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('vatiz-back.posts.index')->with('posts', Post::latest()->paginate(5));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories      = Category::pluck('name', 'id') -> all();
       if(!$categories){
            Session::flash('info', 'You must create a category and tag before attempting to create a post!');
            return redirect() -> route('posts.index');
        }
        return view('vatiz-back.posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $model = new Post;
        $input = $request->all();

        $image = $request->file('image');

        $input['slug'] = str_slug($input['title']);
        $input['author'] = 'Bhatij';
        $string = preg_replace('/<div[^>]+\>/i', "", $string);
        if($image) {
            $input['image'] = $model->uploadImage($image);
        }
        $post = Post::create($input);

        if($post) {
           session()->flash('success', 'Post Created Successfully!');
        } else {
           session()->flash('error', 'Something went wrong.');
        }

        return redirect() -> route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('vatiz-back.posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories      = Category::pluck('name', 'id')->all();
        return view('vatiz-back.posts.create')
                        ->with('post', $post)
                        ->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
      $input = $request->only(['title', 'category_id',  'description','image']);
      $model = new Post;

        $image = $request->file('image');

        $input['slug'] = str_slug($input['title']);
        if($image) {
            if($post->image)
            {
               $model->deleteImage($post->image);
            }
            $input['image'] = $model->uploadImage($image);

        } else {
           $name = explode("/", $post->image);
           $input['image'] = $name[3];
        }

       $input['author'] = 'Bhatij';
       $result = $post->update($input);

        if($result) {
            Session::flash('success', 'Post Updated Successfully!');
        } else {
            Session::flash('error', 'Something went wrong.');
        }

        return redirect() -> route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function trash($id)
    {
        $post = Post::findOrFail($id);
        $result = $post->delete();

         if($result) {
            session()->flash('success', 'Post Trashed Successfully!');
         } else {
            session()->flash('error', 'Something went wrong.');
         }
         return redirect() -> route('posts.index') ;
    }

    public function trashed()
    {
        $posts = Post::onlyTrashed()-> get();

        return view('vatiz-back.posts.trashed', compact('posts'));

    }


    public function delete($id)
    {
        $post = Post::withTrashed() -> where('id', $id) -> first();

        $result = $post->forceDelete();

         if($result) {
            Session::flash('success', 'Post Deleted permanently!');
         } else {
            Session::flash('error', 'Something went wrong.');
         }

         return redirect() -> route('posts.trashed') ;
    }


    public function restore($id)
    {
        $post = Post::withTrashed() -> where('id', $id) -> first();

        $result = $post->restore();

         if($result) {
            Session::flash('success', 'Post Successfully restored!');
         } else {
            Session::flash('error', 'Something went wrong.');
         }

         return redirect() -> route('posts.index') ;

    }
}

resources/views/vatiz-back/posts/create.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<link rel="stylesheet" href="{{ asset('back/css/trix.css') }}" />
<link rel="stylesheet" href="{{ asset('back/css/flatpicker.css') }}" />
<style type="text/css">
	trix-editor {
		height: 500px !important;
		max-height: 200px;
	  	overflow-y: auto !important;
	}

header.panel-heading.custom {
    background: antiquewhite;
    color: sienna;
    font-size: x-large;
    font-family: sans-serif;
    font-weight: 600;
    box-shadow: 3px 3px darkolivegreen;
}

.alert.alert-danger {
    color: firebrick;
    font-size: 16px;
    font-family: sans-serif;
}
</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
	 <div class="panel panel-default">
    <div class="panel-heading">
    @if(isset($post))
     Edit Post
    @else
     Create a Blog Post
    @endif
    </div>

 	@include('partials.errors')
 	<div class="custom" style="padding: 12px">
 		@if(isset($post))
		{!! Form::model($post, ['method'=>'PATCH', 'route' => ['posts.update', $post->id], 'files'=>true]) !!}
		@else
		{{ Form::open(array('method'=>'POST','route' => 'posts.store', 'files'=>true)) }}
		@endif
		<div class="form-group">
			{!! Form::label('title', 'Title : ', ['class' => 'font-weight-bold']) !!}
			{!! Form::text('title', isset($post) ? $post->title : ' ' , ['class' => 'form-control','placeholder'=>'Enter title']) !!}
		</div>

		<div class="form-group">
			{!! Form::label('description', 'Description : ', ['class' => ' font-weight-bold']) !!}
			<input id="x" type="hidden" name="description" value="{{ isset($post) ? $post->description : ' ' }}">
  			<trix-editor input="x"></trix-editor>
		</div>

		@if(isset($post))
		<div class="form-group">
			<img src="{{ asset($post->image) }}" alt="" style="width: 100%;" height="500px">
		</div>
		@endif
		<div class="form-group">
			{!! Form::label('image', 'Image :', ['class' => 'font-weight-bold']) !!}
			{!! Form::file('image',null, ['class' => 'form-control']) !!}
		</div>

        <div class="form-group">
          {!! Form::label('category_id', 'Category:', ['class' => 'font-weight-bold']) !!}
          @if(isset($categories) && count($categories) > 0)
          {!! Form::select('category_id', [''=>'Choose Options'] + $categories , null, ['class'=>'form-control'])!!}
          @endif
        </div>
{{--
		<div class="form-group">
			{!! Form::label('author', 'Author name : ', ['class' => 'font-weight-bold']) !!}
			{!! Form::text('author', isset($post) ? $post->author : ' ' , ['class' => 'form-control','placeholder'=>'Enter author']) !!}
		</div>
 --}}
		<div class="form-group right">
			{{ Form::submit(isset($post) ? 'Update Post' : 'Create Post',['class' => 'btn btn-success'])}}
		</div>
		{!! Form::close() !!}
 	</div>
@include('vatiz-back.layouts.back-footer')
</section>
@endsection

@section('footer')
<script src="{{ asset('back/js/trix.js') }}"></script>
<script src="{{ asset('back/js/flatpicker.js') }}"></script>
<script>
	flatpickr('#published_at', {
		enableTime: true
	})
</script>

@endsection

resources/views/vatiz-back/posts/index.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<style>
	.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
    background: aliceblue;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
	color: royalblue;
}

a:focus, a:hover {
    color: chocolate;
    font-weight: 600;
}

</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     List of All Posts
    </div>
    <div>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Category</th>
            <th data-breakpoints="xs">Title</th>
            <th>Editing</th>
            <th>Trashing</th>
          </tr>
        </thead>
        @if($posts)
        <tbody>
        @foreach($posts as $post)
          <tr>
            <td><img src="{{ asset( $post->image) }}" alt="{{ $post->title }}" height="90px" width="120px"></td>
            <td>{{ $post->category->name }}</td>
            <td> <a href="{{ route('posts.show', $post->id) }}"> {{ $post->title }} </a></td>
      			<td><a href="{{ route('posts.edit', $post -> id) }}" class="btn btn-sm btn-info">Edit</a></td>
      			<td><a href="{{ route('posts.trash', $post -> id) }}" class="btn btn-sm btn-warning">Trash</a></td>
					</tr>
          </tr>
        @endforeach
        </tbody>
        @endif
      </table>
    </div>
    <div style="padding: 12px;background: aliceblue;">
      {{ $posts->links() }}
    </div>
  </div>
</div>

		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>
@endsection

resources/views/vatiz-back/posts/show.blade.php
@extends('vatiz-back.layouts.layout')

@section('content')
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class=" wrapper">
		<div class="agile-grid">
		<h2 class="w3ls_head">{{ $post->title }}</h2>
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <img src="{{ asset($post->image) }}" alt="{{ $post->title }}" height="500px" width="100%" style="padding: 20px">
                        <div class="panel-body">
                            {!! $post->description !!}
                            <div class="clearfix"></div>
                     <a href="#" class="btn btn-primary" style="margin-top: 20px;">{{ $post->category->name }}</a>
                        <div class="buttons pull-right" style="padding: 10px;">
                <a href="{{ route('posts.edit', $post -> id) }}" class="btn btn-info">Edit</a></td>
                <a href="{{ route('posts.trash', $post -> id) }}" class="btn  btn-warning">Trash</a>
                <a href="{{ route('posts.delete', $post -> id) }}" class="btn btn-danger">Delete</a>
                        </div>
                        </div>
                    </section>
                </div>
            </div>
		</div>
        </section>
 <!-- footer -->
		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>

@endsection

resources/views/vatiz-back/posts/trashed.blade.php
@extends('vatiz-back.layouts.layout')

@section('header')
<style>
	.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
    background: aliceblue;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
	color: royalblue;
}
</style>
@endsection

@section('content')
<section id="container">
@include('vatiz-back.layouts.back-header')
<!--header end-->
<!--sidebar start-->
@include('vatiz-back.layouts.sidebar')
<!--sidebar end-->
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     List of All Trashed Posts
    </div>
    <div>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Category</th>
            <th data-breakpoints="xs">Title</th>
            <th>Restore</th>
            <th>Delete</th>
          </tr>
        </thead>
        @if($posts)
        <tbody>
        @foreach($posts as $post)
          <tr>
            <td><img src="{{ $post->image }}" alt="{{ $post->title }}" height="90px" width="120px"></td>
            <td>{{ 'Category' }}</td>
            <td>{{ $post->title }}</td>
      			<td><a href="{{ route('posts.restore', $post -> id) }}" class="btn btn-sm btn-info">Restore</a></td>
      			<td><a href="{{ route('posts.delete', $post -> id) }}" class="btn btn-sm btn-danger">Delete</a></td>
					</tr>
          </tr>
        @endforeach
        </tbody>
        @endif
      </table>
    </div>
  </div>
</div>

		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>
@endsection